# Uncomment the next line to define a global platform for your project
platform :ios, '15.1'

target 'SkillTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkillTalk
  
  # Firebase Core Services
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  
  # Supabase will be added via Swift Package Manager
  # pod 'Supabase' # Not available via CocoaPods
  
  # UI and Networking
  pod 'Alamofire', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SnapKit', '~> 5.0'
  
  # Audio/Video Services
  pod 'AgoraRtcEngine_iOS', '~> 4.0'
  
  # Utilities
  pod 'SwiftyJSON', '~> 5.0'
  pod 'KeychainAccess', '~> 4.0'
  
  target 'SkillTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkillTalkUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      # Disable code signing for pods
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      # Add any needed compiler flags
      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-Xfrontend -warn-concurrency']
    end
  end
end 